# source files in this project 
PROJECT_NAME=c03-quickstart-c++

hello_src  = hello-world.cpp mylib.cpp

iostring_src = io-string.cpp

test_src = mystatslib.cpp \
           test-mystatslib.cpp

process_src = Process.cpp \
              test-Process.cpp

stl_sequence_src = stl-sequence-containers.cpp

stl_map_src = stl-map-containers.cpp

stl_stacks_queues_src = stl-stacks-queues.cpp \
                        Process.cpp

# assignment description documentation
assg_doc  = ${PROJECT_NAME}.pdf

# common targets and variables used for all assignments/projects
include include/Makefile.inc

# assignment header file specific dependencies
