# source files in this project 
PROJECT_NAME=c03-quickstart-c++

hello_src  = hello-world.cpp mylib.cpp

iostring_src = io-string.cpp

test_src = mystatslib.cpp \
           test-mystatslib.cpp

process_src = Process.cpp \
              test-Process.cpp

# assignment description documentation
assg_doc  = ${PROJECT_NAME}.pdf

# common targets and variables used for all assignments/projects
include include/Makefile.inc

# assignment header file specific dependencies
